"""app/services/data_management/restore.py

Restore operations mixin for data management service.
Handles restore preview and full restore execution.
"""

# -- Imports -------------------------------------------------------------------------------------
import logging
from typing import Dict, List, Sequence

from ...dtos.data_management_dtos import (
    FullBackupDTO,
    RestorePreviewDTO,
    RestoreResultDTO,
)
from ...models import (
    Ingredient,
    Meal,
    NutritionFacts,
    PlannerEntry,
    Recipe,
    RecipeGroup,
    RecipeHistory,
    RecipeIngredient,
    ShoppingItem,
    UnitConversionRule,
    UserCategory,
    UserIngredientCategory,
    UserIngredientUnit,
)

logger = logging.getLogger(__name__)

# Mirrors MealService.MAX_SIDE_RECIPES / the Meal.side_recipe_ids setter
MAX_SIDE_RECIPES = 3


# -- Restore Operations Mixin --------------------------------------------------------------------
class RestoreOperationsMixin:
    """Mixin providing restore operations (preview, execute)."""

    # -- Preview Restore -------------------------------------------------------------------------
    def preview_restore(self, backup: FullBackupDTO) -> RestorePreviewDTO:
        """
        Preview what will be restored without making changes.

        Args:
            backup: The backup data to preview.

        Returns:
            RestorePreviewDTO with counts and warnings.
        """
        counts = {
            "ingredients": len(backup.data.ingredients),
            "recipes": len(backup.data.recipes),
            "recipe_ingredients": len(backup.data.recipe_ingredients),
            "recipe_history": len(backup.data.recipe_history),
            "meals": len(backup.data.meals),
            "planner_entries": len(backup.data.planner_entries),
            "shopping_items": len(backup.data.shopping_items),
            "recipe_groups": len(backup.data.recipe_groups),
            "recipe_categories": len(backup.data.recipe_categories),
            "ingredient_categories": len(backup.data.ingredient_categories),
            "ingredient_units": len(backup.data.ingredient_units),
            "conversion_rules": len(backup.data.conversion_rules),
        }

        warnings: List[str] = []

        # Check version compatibility
        if backup.version != "1.0.0":
            warnings.append(f"Backup version {backup.version} may not be fully compatible")

        # Check for existing data
        existing_recipes = (
            self.session.query(Recipe).filter(Recipe.user_id == self._require_user_id()).count()
        )
        if existing_recipes > 0:
            warnings.append(f"Existing data ({existing_recipes} recipes) will be deleted before restore")

        return RestorePreviewDTO(
            backup_version=backup.version,
            backup_created_at=backup.created_at,
            counts=counts,
            has_settings=backup.settings is not None,
            warnings=warnings,
        )

    # -- Execute Restore -------------------------------------------------------------------------
    def execute_restore(
        self, backup: FullBackupDTO, clear_existing: bool = True
    ) -> RestoreResultDTO:
        """
        Execute a full restore from backup.

        The optional clear and the whole reload run in ONE transaction: any
        failure rolls back to the user's original data rather than leaving the
        account half-deleted.

        Restores data in dependency order to maintain referential integrity:
        1. Ingredients (no dependencies)
        2. Recipes (no dependencies) + nutrition facts
        3. Recipe Ingredients (depends on recipes + ingredients)
        4. Recipe History (depends on recipes)
        5. Recipe group membership (depends on recipes)
        6. Meals (depends on recipes)
        7. Planner Entries (depends on meals)
        8. Manual shopping items (recipe items are regenerated by sync)
        9. Categories, units and conversion rules (merged, never cleared)

        Args:
            backup: The backup data to restore.
            clear_existing: If True, clear all existing data first.

        Returns:
            RestoreResultDTO with counts and any errors. Settings are only
            returned on success so a failed restore never half-applies.
        """
        user_id = self._require_user_id()
        errors: List[str] = []
        restored_counts: Dict[str, int] = {}

        try:
            if clear_existing:
                # Keep the Cloudinary images (the backup points at them) and
                # don't commit: the clear only sticks if the reload succeeds
                self.clear_all_data(delete_images=False, commit=False)

            # Build ID mappings as we restore (old_id -> new_id)
            ingredient_id_map: Dict[int, int] = {}
            recipe_id_map: Dict[int, int] = {}
            meal_id_map: Dict[int, int] = {}

            # 1. Restore ingredients (dedupe on name+category, which is unique per user)
            existing_ingredients = {
                (ing.ingredient_name.lower(), ing.ingredient_category.lower()): ing.id
                for ing in self.session.query(Ingredient).filter(Ingredient.user_id == user_id)
            }
            for ing_dto in backup.data.ingredients:
                key = (ing_dto.ingredient_name.lower(), ing_dto.ingredient_category.lower())
                if key not in existing_ingredients:
                    new_ing = Ingredient(
                        ingredient_name=ing_dto.ingredient_name,
                        ingredient_category=ing_dto.ingredient_category,
                        user_id=user_id,
                    )
                    self.session.add(new_ing)
                    self.session.flush()
                    existing_ingredients[key] = new_ing.id
                ingredient_id_map[ing_dto.id] = existing_ingredients[key]
            restored_counts["ingredients"] = len(ingredient_id_map)

            # 2. Restore recipes
            for recipe_dto in backup.data.recipes:
                cook_time = recipe_dto.cook_time
                if cook_time is None and recipe_dto.total_time is not None:
                    cook_time = recipe_dto.total_time
                new_recipe = Recipe(
                    recipe_name=recipe_dto.recipe_name,
                    recipe_category=recipe_dto.recipe_category,
                    meal_type=recipe_dto.meal_type,
                    diet_pref=recipe_dto.diet_pref,
                    description=recipe_dto.description,
                    difficulty=recipe_dto.difficulty,
                    prep_time=recipe_dto.prep_time,
                    cook_time=cook_time,
                    servings=recipe_dto.servings,
                    directions=recipe_dto.directions,
                    notes=recipe_dto.notes,
                    reference_image_path=recipe_dto.reference_image_path,
                    banner_image_path=recipe_dto.banner_image_path,
                    created_at=recipe_dto.created_at,
                    is_favorite=recipe_dto.is_favorite,
                    is_ai_generated=recipe_dto.is_ai_generated,
                    is_sample=recipe_dto.is_sample,
                    source_url=recipe_dto.source_url,
                    user_id=user_id,
                )
                # Preserve the stable image_key so restored recipes keep pointing
                # at their own Cloudinary assets. Older backups without an
                # image_key, or whose key another recipe already holds, fall back
                # to the model-generated default so they never write to that
                # recipe's asset.
                if recipe_dto.image_key and not self._image_key_in_use(recipe_dto.image_key):
                    new_recipe.image_key = recipe_dto.image_key
                self.session.add(new_recipe)
                self.session.flush()
                recipe_id_map[recipe_dto.id] = new_recipe.id
            restored_counts["recipes"] = len(recipe_id_map)

            # 2b. Restore nutrition facts (one per recipe)
            nutrition_count = 0
            seen_nutrition: set = set()
            for nf_dto in backup.data.nutrition_facts:
                new_recipe_id = recipe_id_map.get(nf_dto.recipe_id)
                if not new_recipe_id or new_recipe_id in seen_nutrition:
                    continue
                seen_nutrition.add(new_recipe_id)
                self.session.add(
                    NutritionFacts(
                        **nf_dto.model_dump(exclude={"recipe_id"}),
                        recipe_id=new_recipe_id,
                    )
                )
                nutrition_count += 1
            restored_counts["nutrition_facts"] = nutrition_count

            # 3. Restore recipe ingredients (using mapped IDs). A recipe can only
            # link an ingredient once, so repeated links merge into the first.
            ri_count = 0
            seen_links: set = set()
            for ri_dto in backup.data.recipe_ingredients:
                new_recipe_id = recipe_id_map.get(ri_dto.recipe_id)
                new_ingredient_id = ingredient_id_map.get(ri_dto.ingredient_id)
                if not (new_recipe_id and new_ingredient_id):
                    errors.append("Skipped recipe ingredient: missing recipe or ingredient reference")
                    continue
                if (new_recipe_id, new_ingredient_id) in seen_links:
                    continue
                seen_links.add((new_recipe_id, new_ingredient_id))
                self.session.add(
                    RecipeIngredient(
                        recipe_id=new_recipe_id,
                        ingredient_id=new_ingredient_id,
                        quantity=ri_dto.quantity,
                        unit=ri_dto.unit,
                    )
                )
                ri_count += 1
            restored_counts["recipe_ingredients"] = ri_count

            # 4. Restore recipe history (using mapped recipe IDs)
            history_count = 0
            for rh_dto in backup.data.recipe_history:
                new_recipe_id = recipe_id_map.get(rh_dto.recipe_id)
                if new_recipe_id:
                    self.session.add(
                        RecipeHistory(
                            recipe_id=new_recipe_id,
                            cooked_at=rh_dto.cooked_at,
                            user_id=user_id,
                        )
                    )
                    history_count += 1
                else:
                    errors.append("Skipped recipe history: missing recipe reference")
            restored_counts["recipe_history"] = history_count

            # 5. Restore recipe group membership. Groups aren't cleared, so
            # reuse a same-named group rather than creating a duplicate.
            groups_by_name = {
                g.name.lower(): g
                for g in self.session.query(RecipeGroup).filter(RecipeGroup.user_id == user_id)
            }
            group_count = 0
            for group_dto in backup.data.recipe_groups:
                group = groups_by_name.get(group_dto.name.lower())
                if group is None:
                    group = RecipeGroup(name=group_dto.name, user_id=user_id)
                    self.session.add(group)
                    groups_by_name[group_dto.name.lower()] = group
                member_ids = {r.id for r in group.recipes}
                new_ids = [
                    recipe_id_map[rid]
                    for rid in group_dto.recipe_ids
                    if rid in recipe_id_map and recipe_id_map[rid] not in member_ids
                ]
                if new_ids:
                    group.recipes.extend(
                        self.session.query(Recipe).filter(Recipe.id.in_(new_ids)).all()
                    )
                group_count += 1
            restored_counts["recipe_groups"] = group_count

            # 6. Restore meals (using mapped recipe IDs)
            for meal_dto in backup.data.meals:
                new_main_recipe_id = recipe_id_map.get(meal_dto.main_recipe_id)
                if new_main_recipe_id:
                    new_side_ids: List[int] = []
                    for sid in meal_dto.side_recipe_ids:
                        mapped = recipe_id_map.get(sid)
                        if mapped and mapped != new_main_recipe_id and mapped not in new_side_ids:
                            new_side_ids.append(mapped)
                    new_meal = Meal(
                        meal_name=meal_dto.meal_name,
                        main_recipe_id=new_main_recipe_id,
                        is_saved=meal_dto.is_saved,
                        is_sample=meal_dto.is_sample,
                        created_at=meal_dto.created_at,
                        user_id=user_id,
                    )
                    new_meal.side_recipe_ids = new_side_ids[:MAX_SIDE_RECIPES]
                    new_meal.tags = self._sanitize_tags(meal_dto.tags)
                    self.session.add(new_meal)
                    self.session.flush()
                    meal_id_map[meal_dto.id] = new_meal.id
                else:
                    errors.append(f"Skipped meal '{meal_dto.meal_name}': missing main recipe reference")
            restored_counts["meals"] = len(meal_id_map)

            # 7. Restore planner entries (using mapped meal IDs)
            planner_count = 0
            for pe_dto in backup.data.planner_entries:
                new_meal_id = meal_id_map.get(pe_dto.meal_id)
                if new_meal_id:
                    self.session.add(
                        PlannerEntry(
                            meal_id=new_meal_id,
                            position=pe_dto.position,
                            is_completed=pe_dto.is_completed,
                            completed_at=pe_dto.completed_at,
                            scheduled_date=pe_dto.scheduled_date,
                            shopping_mode=pe_dto.shopping_mode,
                            is_cleared=pe_dto.is_cleared,
                            user_id=user_id,
                        )
                    )
                    planner_count += 1
                else:
                    errors.append("Skipped planner entry: missing meal reference")
            restored_counts["planner_entries"] = planner_count

            # 8. Restore shopping items (only manual items - recipe items will be regenerated by sync)
            manual_items_count = 0
            for si_dto in backup.data.shopping_items:
                if si_dto.source == "manual":
                    self.session.add(
                        ShoppingItem(
                            ingredient_name=si_dto.ingredient_name,
                            quantity=si_dto.quantity,
                            unit=si_dto.unit,
                            category=si_dto.category,
                            source=si_dto.source,
                            have=si_dto.have,
                            flagged=si_dto.flagged,
                            user_id=user_id,
                        )
                    )
                    manual_items_count += 1
            restored_counts["shopping_items"] = manual_items_count

            # 9. Merge customizations. "Delete All Data" never clears these, so
            # they're upserted by slug rather than replaced.
            from ..user_category_service import BUILT_IN_CATEGORIES
            from ..user_ingredient_category_service import BUILT_IN_INGREDIENT_CATEGORIES
            from ..user_ingredient_unit_service import BUILT_IN_UNITS

            restored_counts["recipe_categories"] = self._merge_customizations(
                UserCategory, backup.data.recipe_categories, BUILT_IN_CATEGORIES
            )
            restored_counts["ingredient_categories"] = self._merge_customizations(
                UserIngredientCategory,
                backup.data.ingredient_categories,
                BUILT_IN_INGREDIENT_CATEGORIES,
            )
            restored_counts["ingredient_units"] = self._merge_customizations(
                UserIngredientUnit,
                backup.data.ingredient_units,
                BUILT_IN_UNITS,
                extra_fields=("unit_type",),
            )
            restored_counts["conversion_rules"] = self._merge_conversion_rules(
                backup.data.conversion_rules
            )

            self.session.commit()

        except Exception:
            self.session.rollback()
            logger.exception("Restore failed for user %s", user_id)
            return RestoreResultDTO(
                success=False,
                restored_counts={},
                errors=[
                    "The backup could not be restored, so nothing was changed. "
                    "Check that the file is an unmodified Enchanted Spoon backup."
                ],
                settings=None,
            )

        # 9. Rebuild recipe-driven shopping items. The restore is already
        # committed, so a failure here is a warning, not a failed restore.
        try:
            from ..shopping import ShoppingService

            ShoppingService(self.session, user_id).sync_shopping_list()
        except Exception:
            self.session.rollback()
            logger.exception("Post-restore shopping sync failed for user %s", user_id)
            errors.append(
                "Your data was restored, but the shopping list could not be rebuilt yet. "
                "It will refresh the next time you change your menu."
            )

        return RestoreResultDTO(
            success=True,
            restored_counts=restored_counts,
            errors=errors,
            settings=backup.settings,
        )

    def _merge_customizations(
        self,
        model,
        rows: Sequence,
        built_ins: List[Dict[str, str]],
        extra_fields: Sequence[str] = (),
    ) -> int:
        """Upsert a user's categories/units by slug, keeping any not in the backup.

        A user with none yet is seeded with the built-ins first, exactly as the
        owning service would on first access — otherwise restoring only some
        rows would stop that lazy seeding from ever running.
        """
        if not rows:
            return 0
        user_id = self._require_user_id()
        existing = {
            row.value: row
            for row in self.session.query(model).filter(model.user_id == user_id)
        }
        if not existing:
            for position, item in enumerate(built_ins):
                row = model(
                    user_id=user_id, is_custom=False, is_enabled=True, position=position, **item
                )
                self.session.add(row)
                existing[row.value] = row

        for dto in rows:
            row = existing.get(dto.value)
            if row is None:
                row = model(user_id=user_id, value=dto.value, is_custom=dto.is_custom)
                self.session.add(row)
                existing[dto.value] = row
            row.label = dto.label
            row.is_enabled = dto.is_enabled
            row.position = dto.position
            for field in extra_fields:
                setattr(row, field, getattr(dto, field))
        self.session.flush()
        return len({dto.value for dto in rows})

    def _merge_conversion_rules(self, rules: Sequence) -> int:
        """Upsert conversion rules keyed like the conversion lookup (ingredient, from unit)."""
        if not rules:
            return 0
        user_id = self._require_user_id()
        existing = {
            (rule.ingredient_name.lower().strip(), rule.from_unit.lower().strip()): rule
            for rule in self.session.query(UnitConversionRule).filter(
                UnitConversionRule.user_id == user_id
            )
        }
        for dto in rules:
            key = (dto.ingredient_name, dto.from_unit)
            rule = existing.get(key)
            if rule is None:
                rule = UnitConversionRule(
                    user_id=user_id, ingredient_name=dto.ingredient_name, from_unit=dto.from_unit
                )
                self.session.add(rule)
                existing[key] = rule
            rule.to_unit = dto.to_unit
            rule.factor = dto.factor
            rule.round_up = dto.round_up
        self.session.flush()
        return len({(dto.ingredient_name, dto.from_unit) for dto in rules})

    @staticmethod
    def _sanitize_tags(tags: List[str]) -> List[str]:
        """Coerce backup tags into the Meal model's limits instead of failing the restore."""
        cleaned: List[str] = []
        for tag in tags or []:
            if not isinstance(tag, str):
                continue
            tag = tag.strip()[: Meal.MAX_TAG_LENGTH]
            if tag:
                cleaned.append(tag)
        return cleaned[: Meal.MAX_TAGS]

    def _image_key_in_use(self, image_key: str) -> bool:
        """Whether any recipe (in any account) already holds this image_key."""
        return (
            self.session.query(Recipe.id).filter(Recipe.image_key == image_key).first()
            is not None
        )
